import SwiftUI

struct SafetyDisclaimerView: View {
    let onAccept: () -> Void
    @State private var hasScrolledToBottom = false
    @State private var visibleSections: Set<Int> = []

    private let criticalRed = Color(red: 0.827, green: 0.184, blue: 0.184)

    var body: some View {
        ZStack {
            Color.tradeBg.ignoresSafeArea()

            VStack(spacing: 0) {
                VStack(spacing: 8) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .font(.system(size: 60))
                        .foregroundStyle(Color.modeFaultFinder)
                        .shadow(color: Color.modeFaultFinder.opacity(0.4), radius: 16, x: 0, y: 4)
                        .padding(.top, 32)

                    Text("Important Safety Notice")
                        .font(.system(size: 34, weight: .bold))
                        .tracking(-0.5)
                        .foregroundStyle(Color.tradeText)

                    Text("Please read carefully before using TradeGuru")
                        .font(.system(size: 14))
                        .foregroundStyle(Color.tradeTextSecondary)
                }
                .padding(.bottom, 20)

                ScrollView {
                    VStack(alignment: .leading, spacing: 28) {
                        disclaimerSection(
                            index: 0,
                            number: "1",
                            title: "Not Professional Advice",
                            body: "TradeGuru does not constitute legal, regulatory, compliance, electrical, safety, or professional advice of any kind. The information provided by this application is generated by artificial intelligence and should be treated as a starting point for your own research and verification only."
                        )

                        disclaimerSection(
                            index: 1,
                            number: "2",
                            title: "Not a Substitute for Professional Judgment",
                            body: "TradeGuru must not be relied upon as a substitute for professional judgment, qualified electrical advice, or compliance with applicable Australian Standards (including AS/NZS 3000:2018 Wiring Rules), regulations, state-specific requirements, or industry codes of practice."
                        )

                        disclaimerSection(
                            index: 2,
                            number: "3",
                            title: "Verification Required",
                            body: "You are solely responsible for verifying all information, diagnoses, fault-finding suggestions, and recommendations provided by TradeGuru before taking any action. Always cross-reference with current standards, manufacturer specifications, and local regulatory requirements."
                        )

                        Color.tradeBorder.frame(height: 1)
                            .padding(.vertical, 4)

                        disclaimerSection(
                            index: 3,
                            number: "4",
                            title: "No Responsibility for Outcomes",
                            body: "Trade Guru Pty Ltd accepts no responsibility for any decisions made, actions taken, or work performed based on the application's outputs. All electrical work must be performed by appropriately licensed personnel in accordance with applicable laws and regulations."
                        )

                        disclaimerSection(
                            index: 4,
                            number: "5",
                            title: "Professional Judgment Required",
                            body: "You must always exercise independent professional judgment and comply with all applicable laws, regulations, and safety requirements when performing electrical work. If in doubt, consult a qualified electrical engineer or inspector."
                        )

                        criticalSection(
                            index: 5,
                            number: "6",
                            title: "Inherent Risks",
                            body: "Electrical work is inherently dangerous. Reliance on AI-generated information without proper professional verification could result in property damage, personal injury, or death. You assume all risks associated with the use of this application."
                        )

                        Color.clear
                            .frame(height: 1)
                            .onAppear {
                                DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                                    hasScrolledToBottom = true
                                }
                            }
                    }
                    .padding(.horizontal, 24)
                    .padding(.bottom, 24)
                }

                VStack(spacing: 8) {
                    Color.tradeBorder.frame(height: 1)

                    if !hasScrolledToBottom {
                        HStack(spacing: 6) {
                            Image(systemName: "arrow.down")
                                .font(.system(size: 12))
                            Text("Scroll to read all terms")
                                .font(.system(size: 13))
                        }
                        .foregroundStyle(Color.tradeTextSecondary)
                        .padding(.top, 4)
                    }

                    Button(action: onAccept) {
                        Text("I Understand and Agree")
                            .font(.system(size: 17, weight: .semibold))
                            .foregroundStyle(.white)
                            .frame(maxWidth: .infinity)
                            .frame(height: 56)
                            .background(hasScrolledToBottom ? Color.tradeGreen : Color.tradeTextSecondary)
                            .clipShape(.rect(cornerRadius: 14))
                    }
                    .disabled(!hasScrolledToBottom)
                    .accessibilityLabel("Accept safety disclaimer")
                    .accessibilityHint(hasScrolledToBottom ? "Double tap to accept" : "Scroll to bottom to enable")
                    .animation(.easeOut(duration: 0.3), value: hasScrolledToBottom)
                    .padding(.horizontal, 24)

                    Text("By continuing, you confirm you are a licensed electrical professional")
                        .font(.system(size: 12))
                        .foregroundStyle(Color.tradeTextSecondary)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal, 24)
                        .padding(.bottom, 16)
                }
            }
        }
    }

    private func disclaimerSection(index: Int, number: String, title: String, body: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(alignment: .top, spacing: 10) {
                Text(number)
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(.white)
                    .frame(width: 24, height: 24)
                    .background(Color.modeFaultFinder)
                    .clipShape(.rect(cornerRadius: 7))

                Text(title)
                    .font(.system(size: 17, weight: .semibold))
                    .foregroundStyle(Color.tradeText)
            }

            Text(body)
                .font(.system(size: 15))
                .foregroundStyle(Color.tradeTextSecondary)
                .lineSpacing(4)
                .padding(.leading, 34)
        }
        .opacity(visibleSections.contains(index) ? 1 : 0)
        .offset(y: visibleSections.contains(index) ? 0 : 12)
        .animation(.easeOut(duration: 0.4).delay(Double(index) * 0.08), value: visibleSections.contains(index))
        .onAppear { visibleSections.insert(index) }
    }

    private func criticalSection(index: Int, number: String, title: String, body: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(alignment: .top, spacing: 10) {
                Text(number)
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(.white)
                    .frame(width: 24, height: 24)
                    .background(criticalRed)
                    .clipShape(.rect(cornerRadius: 7))

                Text(title)
                    .font(.system(size: 19, weight: .bold))
                    .foregroundStyle(criticalRed)
            }

            Text(body)
                .font(.system(size: 15))
                .foregroundStyle(Color.tradeTextSecondary)
                .lineSpacing(4)
                .padding(.leading, 34)
        }
        .padding(16)
        .background(criticalRed.opacity(0.08))
        .clipShape(.rect(cornerRadius: 12))
        .opacity(visibleSections.contains(index) ? 1 : 0)
        .offset(y: visibleSections.contains(index) ? 0 : 12)
        .animation(.easeOut(duration: 0.4).delay(Double(index) * 0.08), value: visibleSections.contains(index))
        .onAppear { visibleSections.insert(index) }
    }
}

#Preview {
    SafetyDisclaimerView(onAccept: {})
}
