package com.tradeguru.electrical.ui.views.legal

data class EulaSection(
    val number: String,
    val title: String,
    val body: String,
    val isCritical: Boolean = false
)

val eulaSections = listOf(
    EulaSection(
        "1", "Not Professional Advice",
        "TradeGuru does not constitute legal, regulatory, compliance, electrical, safety, or professional advice of any kind. The information provided by this application is generated by artificial intelligence and should be treated as a starting point for your own research and verification only."
    ),
    EulaSection(
        "2", "Not a Substitute for Professional Judgment",
        "TradeGuru must not be relied upon as a substitute for professional judgment, qualified electrical advice, or compliance with applicable Australian Standards (including AS/NZS 3000:2018 Wiring Rules), regulations, state-specific requirements, or industry codes of practice."
    ),
    EulaSection(
        "3", "Verification Required",
        "You are solely responsible for verifying all information, diagnoses, fault-finding suggestions, and recommendations provided by TradeGuru before taking any action. Always cross-reference with current standards, manufacturer specifications, and local regulatory requirements."
    ),
    EulaSection(
        "4", "No Responsibility for Outcomes",
        "Trade Guru Pty Ltd accepts no responsibility for any decisions made, actions taken, or work performed based on the application\u2019s outputs. All electrical work must be performed by appropriately licensed personnel in accordance with applicable laws and regulations."
    ),
    EulaSection(
        "5", "Professional Judgment Required",
        "You must always exercise independent professional judgment and comply with all applicable laws, regulations, and safety requirements when performing electrical work. If in doubt, consult a qualified electrical engineer or inspector."
    ),
    EulaSection(
        "6", "Inherent Risks",
        "Electrical work is inherently dangerous. Reliance on AI-generated information without proper professional verification could result in property damage, personal injury, or death. You assume all risks associated with the use of this application.",
        isCritical = true
    ),
    EulaSection(
        "7", "AI Limitations",
        "TradeGuru uses artificial intelligence models that may produce inaccurate, incomplete, outdated, or misleading information. AI responses are probabilistic in nature and may contain errors, hallucinations, or omissions. The AI does not have access to your specific site conditions, existing installations, or local amendments to national standards."
    ),
    EulaSection(
        "8", "Standards and Regulations",
        "Australian electrical standards and regulations are subject to change. TradeGuru\u2019s training data may not reflect the most recent amendments, state-specific variations, or local authority requirements. Always confirm compliance with the current edition of AS/NZS 3000, AS/NZS 3008, AS/NZS 3012, and any applicable state or territory regulations."
    ),
    EulaSection(
        "9", "Licensing Requirements",
        "All electrical work in Australia must be performed by appropriately licensed electricians in accordance with state and territory licensing requirements. TradeGuru is intended as a reference tool for licensed professionals only and must not be used by unlicensed persons to perform electrical work."
    ),
    EulaSection(
        "10", "No Warranty",
        "TradeGuru is provided \u201Cas is\u201D and \u201Cas available\u201D without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. Trade Guru Pty Ltd does not warrant that the application will be uninterrupted, error-free, or free of harmful components."
    ),
    EulaSection(
        "11", "Limitation of Liability",
        "To the maximum extent permitted by law, Trade Guru Pty Ltd, its directors, employees, agents, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the application, including but not limited to property damage, personal injury, loss of profits, or loss of data.",
        isCritical = true
    ),
    EulaSection(
        "12", "Indemnification",
        "You agree to indemnify, defend, and hold harmless Trade Guru Pty Ltd, its directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising from your use of the application, your violation of these terms, or your violation of any applicable law or regulation."
    ),
    EulaSection(
        "13", "Data and Privacy",
        "TradeGuru may collect and process data including your queries, device information, and usage patterns to improve the service. Your data is handled in accordance with our Privacy Policy and the Australian Privacy Principles under the Privacy Act 1988 (Cth). Conversation data may be sent to third-party AI providers for processing."
    ),
    EulaSection(
        "14", "Intellectual Property",
        "All content, features, and functionality of TradeGuru are owned by Trade Guru Pty Ltd and are protected by Australian and international copyright, trademark, and other intellectual property laws. You may not reproduce, distribute, modify, or create derivative works from any content provided by the application without prior written consent."
    ),
    EulaSection(
        "15", "Third-Party Services",
        "TradeGuru may integrate with or reference third-party services, standards databases, and manufacturer specifications. Trade Guru Pty Ltd is not responsible for the accuracy, availability, or content of any third-party services. Links to third-party resources are provided for convenience only and do not imply endorsement."
    ),
    EulaSection(
        "16", "Modification of Terms",
        "Trade Guru Pty Ltd reserves the right to modify these terms at any time. Continued use of the application after changes constitutes acceptance of the revised terms. Material changes will be communicated through the application or via email where possible."
    ),
    EulaSection(
        "17", "Governing Law",
        "These terms are governed by and construed in accordance with the laws of Australia. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts of Australia."
    ),
    EulaSection(
        "18", "Severability",
        "If any provision of these terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect. The invalid or unenforceable provision shall be modified to the minimum extent necessary to make it valid and enforceable."
    ),
    EulaSection(
        "19", "Entire Agreement",
        "These terms, together with the Privacy Policy and any additional terms presented within the application, constitute the entire agreement between you and Trade Guru Pty Ltd regarding the use of TradeGuru. These terms supersede all prior agreements, representations, and understandings."
    )
)

val acknowledgementItems = listOf(
    "I am a licensed electrical professional or am supervised by one.",
    "I will verify all AI-generated information against current standards before acting.",
    "I understand TradeGuru is an AI tool and may produce inaccurate information.",
    "I accept all risks associated with using AI-generated electrical guidance.",
    "I have read, understood, and agree to all 19 sections of this disclaimer."
)
